spring.application.name=resumeanalyzer

# Added allowPublicKeyRetrieval=true to the end of this line
spring.datasource.url=jdbc:mysql://localhost:3306/resume_analyzer?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=922988
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true